/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SubjectsRouteImport } from './routes/subjects'
import { Route as StudentScanRouteImport } from './routes/student-scan'
import { Route as StudentDashboardRouteImport } from './routes/student-dashboard'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as QrcodeGeneratorRouteImport } from './routes/qrcode-generator'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminDashboardRouteImport } from './routes/admin-dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AttendanceSessionLectureIdRouteImport } from './routes/attendance-session.$lectureId'

const SubjectsRoute = SubjectsRouteImport.update({
  id: '/subjects',
  path: '/subjects',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentScanRoute = StudentScanRouteImport.update({
  id: '/student-scan',
  path: '/student-scan',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentDashboardRoute = StudentDashboardRouteImport.update({
  id: '/student-dashboard',
  path: '/student-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const QrcodeGeneratorRoute = QrcodeGeneratorRouteImport.update({
  id: '/qrcode-generator',
  path: '/qrcode-generator',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin-dashboard',
  path: '/admin-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AttendanceSessionLectureIdRoute =
  AttendanceSessionLectureIdRouteImport.update({
    id: '/attendance-session/$lectureId',
    path: '/attendance-session/$lectureId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin-dashboard': typeof AdminDashboardRoute
  '/login': typeof LoginRoute
  '/qrcode-generator': typeof QrcodeGeneratorRoute
  '/reports': typeof ReportsRoute
  '/student-dashboard': typeof StudentDashboardRoute
  '/student-scan': typeof StudentScanRoute
  '/subjects': typeof SubjectsRoute
  '/attendance-session/$lectureId': typeof AttendanceSessionLectureIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin-dashboard': typeof AdminDashboardRoute
  '/login': typeof LoginRoute
  '/qrcode-generator': typeof QrcodeGeneratorRoute
  '/reports': typeof ReportsRoute
  '/student-dashboard': typeof StudentDashboardRoute
  '/student-scan': typeof StudentScanRoute
  '/subjects': typeof SubjectsRoute
  '/attendance-session/$lectureId': typeof AttendanceSessionLectureIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin-dashboard': typeof AdminDashboardRoute
  '/login': typeof LoginRoute
  '/qrcode-generator': typeof QrcodeGeneratorRoute
  '/reports': typeof ReportsRoute
  '/student-dashboard': typeof StudentDashboardRoute
  '/student-scan': typeof StudentScanRoute
  '/subjects': typeof SubjectsRoute
  '/attendance-session/$lectureId': typeof AttendanceSessionLectureIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin-dashboard'
    | '/login'
    | '/qrcode-generator'
    | '/reports'
    | '/student-dashboard'
    | '/student-scan'
    | '/subjects'
    | '/attendance-session/$lectureId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin-dashboard'
    | '/login'
    | '/qrcode-generator'
    | '/reports'
    | '/student-dashboard'
    | '/student-scan'
    | '/subjects'
    | '/attendance-session/$lectureId'
  id:
    | '__root__'
    | '/'
    | '/admin-dashboard'
    | '/login'
    | '/qrcode-generator'
    | '/reports'
    | '/student-dashboard'
    | '/student-scan'
    | '/subjects'
    | '/attendance-session/$lectureId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  LoginRoute: typeof LoginRoute
  QrcodeGeneratorRoute: typeof QrcodeGeneratorRoute
  ReportsRoute: typeof ReportsRoute
  StudentDashboardRoute: typeof StudentDashboardRoute
  StudentScanRoute: typeof StudentScanRoute
  SubjectsRoute: typeof SubjectsRoute
  AttendanceSessionLectureIdRoute: typeof AttendanceSessionLectureIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/subjects': {
      id: '/subjects'
      path: '/subjects'
      fullPath: '/subjects'
      preLoaderRoute: typeof SubjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student-scan': {
      id: '/student-scan'
      path: '/student-scan'
      fullPath: '/student-scan'
      preLoaderRoute: typeof StudentScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student-dashboard': {
      id: '/student-dashboard'
      path: '/student-dashboard'
      fullPath: '/student-dashboard'
      preLoaderRoute: typeof StudentDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qrcode-generator': {
      id: '/qrcode-generator'
      path: '/qrcode-generator'
      fullPath: '/qrcode-generator'
      preLoaderRoute: typeof QrcodeGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-dashboard': {
      id: '/admin-dashboard'
      path: '/admin-dashboard'
      fullPath: '/admin-dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attendance-session/$lectureId': {
      id: '/attendance-session/$lectureId'
      path: '/attendance-session/$lectureId'
      fullPath: '/attendance-session/$lectureId'
      preLoaderRoute: typeof AttendanceSessionLectureIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  LoginRoute: LoginRoute,
  QrcodeGeneratorRoute: QrcodeGeneratorRoute,
  ReportsRoute: ReportsRoute,
  StudentDashboardRoute: StudentDashboardRoute,
  StudentScanRoute: StudentScanRoute,
  SubjectsRoute: SubjectsRoute,
  AttendanceSessionLectureIdRoute: AttendanceSessionLectureIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
